package api

type Assignment struct {
	AllDates                        interface{} `json:"all_dates"`
	AllowedAttempts                 int64       `json:"allowed_attempts"`
	AllowedExtensions               []string    `json:"allowed_extensions"`
	AnonymousGrading                bool        `json:"anonymous_grading"`
	AnonymousSubmissions            bool        `json:"anonymous_submissions"`
	AssignmentGroupID               int64       `json:"assignment_group_id"`
	AssignmentVisibility            []int64     `json:"assignment_visibility"`
	AutomaticPeerReviews            bool        `json:"automatic_peer_reviews"`
	CanSubmit                       bool        `json:"can_submit"`
	CourseID                        int64       `json:"course_id"`
	CreatedAt                       string      `json:"created_at"`
	Description                     string      `json:"description"`
	DiscussionTopic                 interface{} `json:"discussion_topic"`
	DueAt                           string      `json:"due_at"`
	DueDateRequired                 bool        `json:"due_date_required"`
	ExternalToolTagAttributes       interface{} `json:"external_tool_tag_attributes"`
	FinalGraderID                   int64       `json:"final_grader_id"`
	FreezeOnCopy                    bool        `json:"freeze_on_copy"`
	Frozen                          bool        `json:"frozen"`
	FrozenAttributes                []string    `json:"frozen_attributes"`
	GradeGroupStudentsIndividually  bool        `json:"grade_group_students_individually"`
	GraderCommentsVisibleToGraders  bool        `json:"grader_comments_visible_to_graders"`
	GraderCount                     int64       `json:"grader_count"`
	GraderNamesVisibleToFinalGrader bool        `json:"grader_names_visible_to_final_grader"`
	GradersAnonymousToGraders       bool        `json:"graders_anonymous_to_graders"`
	GradingStandardID               interface{} `json:"grading_standard_id"`
	GradingType                     string      `json:"grading_type"`
	GroupCategoryID                 int64       `json:"group_category_id"`
	HasOverrides                    bool        `json:"has_overrides"`
	HasSubmittedSubmissions         bool        `json:"has_submitted_submissions"`
	HTMLURL                         string      `json:"html_url"`
	ID                              int64       `json:"id"`
	IntegrationID                   string      `json:"integration_id"`
	IntraGroupPeerReviews           bool        `json:"intra_group_peer_reviews"`
	LockAt                          string      `json:"lock_at"`
	LockExplanation                 string      `json:"lock_explanation"`
	LockInfo                        interface{} `json:"lock_info"`
	LockedForUser                   bool        `json:"locked_for_user"`
	MaxNameLength                   int64       `json:"max_name_length"`
	ModeratedGrading                bool        `json:"moderated_grading"`
	Name                            string      `json:"name"`
	NeedsGradingCount               int64       `json:"needs_grading_count"`
	NeedsGradingCountBySection      []struct {
		NeedsGradingCount int64  `json:"needs_grading_count"`
		SectionID         string `json:"section_id"`
	} `json:"needs_grading_count_by_section"`
	OmitFromFinalGrade     bool        `json:"omit_from_final_grade"`
	OnlyVisibleToOverrides bool        `json:"only_visible_to_overrides"`
	Overrides              interface{} `json:"overrides"`
	PeerReviewCount        int64       `json:"peer_review_count"`
	PeerReviews            bool        `json:"peer_reviews"`
	PeerReviewsAssignAt    string      `json:"peer_reviews_assign_at"`
	PointsPossible         int64       `json:"points_possible"`
	Position               int64       `json:"position"`
	PostManually           bool        `json:"post_manually"`
	PostToSis              bool        `json:"post_to_sis"`
	Published              bool        `json:"published"`
	QuizID                 int64       `json:"quiz_id"`
	Rubric                 interface{} `json:"rubric"`
	RubricSettings         interface{} `json:"rubric_settings"`
	ScoreStatistics        interface{} `json:"score_statistics"`
	Submission             interface{} `json:"submission"`
	SubmissionTypes        []string    `json:"submission_types"`
	SubmissionsDownloadURL string      `json:"submissions_download_url"`
	TurnitinEnabled        bool        `json:"turnitin_enabled"`
	TurnitinSettings       interface{} `json:"turnitin_settings"`
	UnlockAt               string      `json:"unlock_at"`
	Unpublishable          bool        `json:"unpublishable"`
	UpdatedAt              string      `json:"updated_at"`
	UseRubricForGrading    bool        `json:"use_rubric_for_grading"`
	VericiteEnabled        bool        `json:"vericite_enabled"`
}
